// 存放静态的mutation common
export const SET_SIDEBAR_COLLAPSE = 'SET_SIDEBAR_COLLAPSE'
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'
export const DELETE_TAGS_ITEM = 'DELETE_TAGS_ITEM'
export const SET_TAGS_LIST = 'SET_TAGS_LIST'
export const SET_BREADCRUMB_LIST = 'SET_BREADCRUMB_LIST'
export const PUSH_BREADCRUMB_LIST = 'PUSH_BREADCRUMB_LIST'
export const SET_PROJECT_LIST = 'SET_PROJECT_LIST'
export const SET_CUR_PROJECT = 'SET_CUR_PROJECT'
export const SET_QUOTA_LIST = 'SET_QUOTA_LIST'
export const SET_QUOTA_LOADING = 'SET_QUOTA_LOADING'

// 不在缓存区域的字段
export const SET_ALLUSER_LIST = 'SET_ALLUSER_LIST'
export const SET_SECURITY_INFO = 'SET_SECURITY_INFO'
// 创建虚拟机 缓存的列表信息
export const INSTANCE_INIT_FINISH = 'INSTANCE_INIT_FINISH'
export const INSTANCE_INIT_IMAGE = 'INSTANCE_INIT_IMAGE'
export const INSTANCE_INIT_SSHKEY = 'INSTANCE_INIT_SSHKEY'
export const INSTANCE_INIT_SERVER_GROUP = 'INSTANCE_INIT_SERVER_GROUP'
export const INSTANCE_INIT_FLAVOR = 'INSTANCE_INIT_FLAVOR'
export const INSTANCE_INIT_SECURITY = 'INSTANCE_INIT_SECURITY'
export const INSTANCE_INIT_NETWORK = 'INSTANCE_INIT_NETWORK'

// 登录以及个人信息 mutation
export const SET_USERINFO = 'SET_USERINFO'
export const LOGIN_OUT = 'LOGIN_OUT'
export const LOGIN_TIME = 'LOGIN_TIME'
export const USER_AUTH = 'USER_AUTH'
export const USER_MENU = 'USER_MENU'
